"""add room join table

Revision ID: 080aaad0f60f
Revises: 0b4b39789441
Create Date: 2023-08-16 01:27:07.684043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '080aaad0f60f'
down_revision: Union[str, None] = '0b4b39789441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_character_enemy',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('room name', sa.String(), nullable=True),
    sa.Column('room type', sa.String(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('enemy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['enemy_id'], ['enemies.id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_character_enemy')
    # ### end Alembic commands ###
