"""create room table

Revision ID: cf98c7c367de
Revises: dafa6a30b011
Create Date: 2023-08-15 23:08:59.251986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf98c7c367de'
down_revision: Union[str, None] = 'dafa6a30b011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('room_type', sa.String(), nullable=True),
    sa.Column('char_id', sa.Integer(), nullable=True),
    sa.Column('enemy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['char_id'], ['enemies.id'], ),
    sa.ForeignKeyConstraint(['enemy_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    # ### end Alembic commands ###
