"""create enemy table

Revision ID: ebab82de1e6d
Revises: 1ae190ac3351
Create Date: 2023-08-15 16:52:34.320778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebab82de1e6d'
down_revision: Union[str, None] = '1ae190ac3351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enemies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('health_point', sa.Integer(), nullable=True),
    sa.Column('attack_point', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enemies')
    # ### end Alembic commands ###
